/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './hooks/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'min-h-screen',
    'bg-background',
    'bg-card',
    'bg-primary',
    'bg-secondary',
    'bg-muted',
    'bg-accent',
    'text-foreground',
    'text-muted-foreground',
    'text-primary',
    'text-primary-foreground',
    'border',
    'border-border',
    'rounded-xl',
    'rounded-lg',
    'rounded-md',
    'rounded-full',
    'shadow-sm',
    'shadow-md',
    'p-3',
    'p-4',
    'p-5',
    'p-6',
    'px-3',
    'px-4',
    'py-2',
    'py-4',
    'py-6',
    'mt-1',
    'mt-2',
    'mt-3',
    'mt-4',
    'mb-2',
    'mb-4',
    'mx-auto',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    'space-y-1',
    'space-y-2',
    'space-y-4',
    'space-y-6',
    'flex',
    'inline-flex',
    'grid',
    'hidden',
    'block',
    'flex-col',
    'flex-row',
    'items-center',
    'items-start',
    'justify-center',
    'justify-between',
    'justify-end',
    'w-full',
    'h-full',
    'h-4',
    'h-5',
    'w-4',
    'w-5',
    'text-xs',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-center',
    'tracking-tight',
    'border-b',
    'container',
    'grid-cols-2',
    'transition-all',
    'transition-colors',
    'antialiased',
    'text-green-500',
    'text-red-500',
    'text-blue-500',
    'text-orange-500',
    {
      pattern: /bg-(primary|secondary|muted|accent|card|background|popover|destructive)(\/[0-9]+)?/,
    },
    {
      pattern: /text-(primary|secondary|muted|accent|card|foreground|destructive)(-foreground)?(\/[0-9]+)?/,
    },
    {
      pattern: /border-(primary|secondary|muted|accent|border|input|ring)(\/[0-9]+)?/,
    },
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
